USE [LiveBagelAMPM_Prod]
GO
/****** Object:  StoredProcedure [dbo].[sp_Item_DoughType_Details]    Script Date: 7/29/2025 1:22:54 PM ******/
IF EXISTS (SELECT NULL FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[sp_Item_DoughType_Details]') AND TYPE IN (N'P'))
BEGIN
	DROP PROCEDURE [dbo].[sp_Item_DoughType_Details];
END
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE PROC  [dbo].[sp_Item_DoughType_Details]

	@StartDate AS DATETIME,
	@EndDate AS DATETIME ,
	@Itemnbr AS VARCHAR(25),
	@AspectID AS INT 

AS
/*****************************************************************
///<spcomments>
///	<spname>[dbo].[sp_Item_DoughType_Details]</spname>
///	<summary></summary>
///	<callers>
///		<caller></caller>
///	</callers>
///	<calls>
///		<call>Database</call>
///	</calls>
///	<dependents>
///		<dependent></dependent>
///	</dependents>
///	<history>
		Date:		By:		Comments:
		10/09/2025	Soumendu	OPTIMIZED
///	</history>
///	<example>
///		<code>
///		</code>
///	</example>
///</spcomments>
*****************************************************************/
BEGIN
	SET NOCOUNT ON;

	IF @AspectID = 1	--What got produced
	BEGIN 

	 
		SELECT 

			TRANSACTIONID = trn.trid ,
			TRANTYPE = tt.ITTDESC  ,
			TRANDATE = dbo.getShortDate(trn.TRDATETIME) + ' ' + dbo.getShortTime(trn.TRDATETIME),
			TRANCASES = trn.TRCASES,
			TRANORIGINALVALUE = ISNULL(trn.TRORIGINALVALUE,0),
			TRANNEWVALUE = ISNULL(trn.TRNEWVALUE,0),
			CUSTOMER = ISNULL(	lp.LABELCUSTOMERINFO, 
								CONVERT(VARCHAR , lso.ORDERNBR)  + ' : ' + UPPER (lso.CUSTOMERNAME)
							  )
		FROM dbo.ITEMTRANSACTION trn
		INNER JOIN dbo.ITEMTRANSACTIONTYPE tt ON trn.TRTYPEID = tt.ITTID
		LEFT JOIN dbo.ITEMALLOCATION allo ON allo.IATRANSID = trn.TRID
		LEFT JOIN dbo.LABELS_PRODUCTION lp ON lp.LABELSERIALNBR = allo.IALABELSERIALNBR
		LEFT JOIN LiveSalesorder lso ON lso.ORDERNBR = allo.IAORDERNBR
		WHERE TRTYPEID IN (1,8, 17) --1=PRODUCTION, 8=ADD TO INVENTORY, 17=ADD TO INVENTORY EXTERNAL ITEM
		AND trn.TRITEMNBR = @ItemNbr
		AND CONVERT(DATE, TRDATETIME) >= @StartDate AND CONVERT(DATE, TRDATETIME) < = @EndDate

		UNION ALL

		SELECT 

			TRANSACTIONID = trn.trid ,
			TRANTYPE = tt.ITTDESC  ,
			TRANDATE = dbo.getShortDate(trn.TRDATETIME) + ' ' + dbo.getShortTime(trn.TRDATETIME),
			TRANCASES = trn.TRCASES,
			TRANORIGINALVALUE = ISNULL(trn.TRORIGINALVALUE,0),
			TRANNEWVALUE = ISNULL(trn.TRNEWVALUE,0),
			CUSTOMER = ISNULL(	lp.LABELCUSTOMERINFO, 
								CONVERT(VARCHAR , lso.ORDERNBR)  + ' : ' + UPPER (lso.CUSTOMERNAME)
							  )
		FROM dbo.ITEMTRANSACTION_ARCHIVE trn
		INNER JOIN dbo.ITEMTRANSACTIONTYPE tt ON trn.TRTYPEID = tt.ITTID
		LEFT JOIN dbo.ITEMALLOCATION_ARCHIVE allo ON allo.IATRANSID = trn.TRID
		LEFT JOIN dbo.LABELS_PRODUCTION lp ON lp.LABELSERIALNBR = allo.IALABELSERIALNBR
		LEFT JOIN LIVESALESORDER_ARCHIVE lso ON lso.ORDERNBR = allo.IAORDERNBR
		WHERE TRTYPEID IN (1,8,17) --1=PRODUCTION, 8=ADD TO INVENTORY, 17=ADD TO INVENTORY EXTERNAL ITEM
		AND trn.TRITEMNBR = @ItemNbr
		AND CONVERT(DATE, TRDATETIME) >= @StartDate AND CONVERT(DATE, TRDATETIME) < = @EndDate

		UNION ALL

		SELECT 

			TRANSACTIONID = trn.trid ,
			TRANTYPE = tt.ITTDESC  ,
			TRANDATE = dbo.getShortDate(trn.TRDATETIME) + ' ' + dbo.getShortTime(trn.TRDATETIME),
			TRANCASES = trn.TRCASES,
			TRANORIGINALVALUE = ISNULL(trn.TRORIGINALVALUE,0),
			TRANNEWVALUE = ISNULL(trn.TRNEWVALUE,0),
			CUSTOMER = ISNULL(	lp.LABELCUSTOMERINFO, 
								CONVERT(VARCHAR , lso.ORDERNBR)  + ' : ' + UPPER (lso.CUSTOMERNAME)
							  )
		FROM LiveBagelAMPM_FEB_05.dbo.ITEMTRANSACTION trn
		INNER JOIN LiveBagelAMPM_FEB_05.dbo.ITEMTRANSACTIONTYPE tt ON trn.TRTYPEID = tt.ITTID
		LEFT JOIN LiveBagelAMPM_FEB_05.dbo.ITEMALLOCATION allo ON allo.IATRANSID = trn.TRID
		LEFT JOIN LiveBagelAMPM_FEB_05.dbo.LABELS_PRODUCTION lp ON lp.LABELSERIALNBR = allo.IALABELSERIALNBR
		LEFT JOIN LiveBagelAMPM_FEB_05.dbo.LiveSalesorder lso ON lso.ORDERNBR = allo.IAORDERNBR
		WHERE TRTYPEID IN (1,8,17) --1=PRODUCTION, 8=ADD TO INVENTORY, 17=ADD TO INVENTORY EXTERNAL ITEM
		AND trn.TRITEMNBR = @ItemNbr
		AND CONVERT(DATE, TRDATETIME) >= @StartDate AND CONVERT(DATE, TRDATETIME) < = @EndDate
		ORDER BY  1 DESC , 3 DESC 
	END 


	IF @AspectID = 2	--What got Allocated
	BEGIN 

	--;WITH cte
	--AS( 
	--	SELECT DISTINCT OutTransactionID FROM InventoryItemTracker WHERE ItemNbr = @ItemNbr AND OutTransactionId IS NOT NULL)
	--)
		;WITH CTE AS (
			SELECT
				TRANSACTIONID = trn.TRID,
				TRANTYPE      = tt.ITTDESC + ' From Lot- ' + ISNULL(CONVERT(VARCHAR(10), iss.IssueDate, 1), ''),
				--LOT_NO      = ISNULL(CONVERT(VARCHAR(10), iss.IssueDate, 1), '-'),
				TRANDATE = dbo.getShortDate(trn.TRDATETIME) 
						   + ' ' + dbo.getShortTime(trn.TRDATETIME),

				
				TRANCASES = CASE 
								WHEN alloc.AllocationQuantity IS NULL THEN trn.TRCASES
								ELSE -alloc.AllocationQuantity
							END,

				TRANORIGINALVALUE = ISNULL(trn.TRORIGINALVALUE, 0),
				TRANNEWVALUE      = ISNULL(trn.TRNEWVALUE, 0),

				CUSTOMER = ISNULL(
								lp.LABELCUSTOMERINFO,
								CONVERT(VARCHAR, lso.ORDERNBR) + ' : ' + UPPER(lso.CUSTOMERNAME)
						   )

			FROM dbo.ITEMTRANSACTION trn
			INNER JOIN dbo.ITEMTRANSACTIONTYPE tt
					ON trn.TRTYPEID = tt.ITTID

			LEFT JOIN dbo.ITEMALLOCATION allo
				   ON allo.IATRANSID = trn.TRID

			LEFT JOIN dbo.LABELS_PRODUCTION lp
				   ON lp.LABELSERIALNBR = allo.IALABELSERIALNBR

			LEFT JOIN LiveSalesorder lso
				   ON lso.ORDERNBR = allo.IAORDERNBR

			
			LEFT JOIN InventoryItemTracker alloc
				   ON alloc.OutTransactionId = trn.TRID
				  AND alloc.ItemNbr = @ItemNbr

			
			LEFT JOIN InventoryItemTracker iss
				   ON iss.InTransactionId = alloc.InTransactionId
				  AND iss.ItemNbr = @ItemNbr
				  AND iss.IssueDate IS NOT NULL
			WHERE TRTYPEID IN (2,14)	--- 2=ALLOCATE TO ORDER, 14=INVENTORY ALLOCATION FOR ORDER
			AND trn.TRITEMNBR = @ItemNbr
			AND CONVERT(DATE, TRDATETIME) >= @StartDate AND CONVERT(DATE, TRDATETIME) < = @EndDate

			UNION ALL

			SELECT 

				TRANSACTIONID = trn.trid ,
				TRANTYPE = tt.ITTDESC + ' From Lot- ',
				--LOT_NO      = '-',
				TRANDATE = dbo.getShortDate(trn.TRDATETIME) + ' ' + dbo.getShortTime(trn.TRDATETIME),
				TRANCASES = trn.TRCASES,
				TRANORIGINALVALUE = ISNULL(trn.TRORIGINALVALUE,0),
				TRANNEWVALUE = ISNULL(trn.TRNEWVALUE,0),
				CUSTOMER = ISNULL(	lp.LABELCUSTOMERINFO, 
									CONVERT(VARCHAR , lso.ORDERNBR)  + ' : ' + UPPER (lso.CUSTOMERNAME)
								  )

			FROM ITEMTRANSACTION_ARCHIVE trn
			INNER JOIN ITEMTRANSACTIONTYPE tt ON trn.TRTYPEID = tt.ITTID
			LEFT JOIN ITEMALLOCATION_ARCHIVE allo ON allo.IATRANSID = trn.TRID
			LEFT JOIN LABELS_PRODUCTION lp ON lp.LABELSERIALNBR = allo.IALABELSERIALNBR
			LEFT JOIN LIVESALESORDER_ARCHIVE lso ON lso.ORDERNBR = allo.IAORDERNBR
	 
			WHERE TRTYPEID IN (2,14)	--- 2=ALLOCATE TO ORDER, 14=INVENTORY ALLOCATION FOR ORDER
			AND trn.TRITEMNBR = @ItemNbr
			AND CONVERT(DATE, TRDATETIME) >= @StartDate AND CONVERT(DATE, TRDATETIME) < = @EndDate

			UNION ALL
  
			SELECT 

				TRANSACTIONID = trn.trid ,
				TRANTYPE = tt.ITTDESC + ' From Lot- ',
				--LOT_NO      = '-',
				TRANDATE = dbo.getShortDate(trn.TRDATETIME) + ' ' + dbo.getShortTime(trn.TRDATETIME),
				TRANCASES = trn.TRCASES,
				TRANORIGINALVALUE = ISNULL(trn.TRORIGINALVALUE,0),
				TRANNEWVALUE = ISNULL(trn.TRNEWVALUE,0),
				CUSTOMER = ISNULL(	lp.LABELCUSTOMERINFO, 
									CONVERT(VARCHAR , lso.ORDERNBR)  + ' : ' + UPPER (lso.CUSTOMERNAME)
								  )

			FROM LiveBagelAMPM_FEB_05.dbo.ITEMTRANSACTION trn
			INNER JOIN LiveBagelAMPM_FEB_05.dbo.ITEMTRANSACTIONTYPE tt ON trn.TRTYPEID = tt.ITTID
			LEFT JOIN LiveBagelAMPM_FEB_05.dbo.ITEMALLOCATION allo ON allo.IATRANSID = trn.TRID
			LEFT JOIN LiveBagelAMPM_FEB_05.dbo.LABELS_PRODUCTION lp ON lp.LABELSERIALNBR = allo.IALABELSERIALNBR
			LEFT JOIN LiveBagelAMPM_FEB_05.dbo.LiveSalesorder lso ON lso.ORDERNBR = allo.IAORDERNBR
	 
			WHERE TRTYPEID IN (2,14)	--- 2=ALLOCATE TO ORDER, 14=INVENTORY ALLOCATION FOR ORDER
			AND trn.TRITEMNBR = @ItemNbr
			AND CONVERT(DATE, TRDATETIME) >= @StartDate AND CONVERT(DATE, TRDATETIME) < = @EndDate
		)

		SELECT DISTINCT TRANSACTIONID,TRANTYPE,/*LOT_NO,*/TRANDATE,TRANCASES,TRANORIGINALVALUE,TRANNEWVALUE,CUSTOMER
		FROM CTE
		ORDER BY  1 DESC , 3 DESC; 
	END 


	IF @AspectID = 3	--What got Adjusted 
	BEGIN 
	 
		SELECT 

			TRANSACTIONID = trn.trid ,
			TRANTYPE = tt.ITTDESC,
			TRANDATE = dbo.getShortDate(trn.TRDATETIME) + ' ' + dbo.getShortTime(trn.TRDATETIME),
			TRANCASES = trn.TRCASES,
			TRANORIGINALVALUE = ISNULL(trn.TRORIGINALVALUE,0),
			TRANNEWVALUE = ISNULL(trn.TRNEWVALUE,0),
			CUSTOMER = ISNULL(	lp.LABELCUSTOMERINFO, 
								CONVERT(VARCHAR , lso.ORDERNBR)  + ' : ' + UPPER (lso.CUSTOMERNAME)
							  )
		FROM dbo.ITEMTRANSACTION trn
		INNER JOIN dbo.ITEMTRANSACTIONTYPE tt ON trn.TRTYPEID = tt.ITTID
		LEFT JOIN dbo.ITEMALLOCATION allo ON allo.IATRANSID = trn.TRID
		LEFT JOIN dbo.LABELS_PRODUCTION lp ON lp.LABELSERIALNBR = allo.IALABELSERIALNBR
		LEFT JOIN LiveSalesorder lso ON lso.ORDERNBR = allo.IAORDERNBR
		WHERE TRTYPEID IN (3,4,5,6,7,9,10,11,12,13) 	 
		AND trn.TRITEMNBR = @ItemNbr
		AND CONVERT(DATE, TRDATETIME) >= @StartDate AND CONVERT(DATE, TRDATETIME) < = @EndDate

		UNION ALL

		SELECT 

			TRANSACTIONID = trn.trid ,
			TRANTYPE = tt.ITTDESC,
			TRANDATE = dbo.getShortDate(trn.TRDATETIME) + ' ' + dbo.getShortTime(trn.TRDATETIME),
			TRANCASES = trn.TRCASES,
			TRANORIGINALVALUE = ISNULL(trn.TRORIGINALVALUE,0),
			TRANNEWVALUE = ISNULL(trn.TRNEWVALUE,0),
			CUSTOMER = ISNULL(	lp.LABELCUSTOMERINFO, 
								CONVERT(VARCHAR , lso.ORDERNBR)  + ' : ' + UPPER (lso.CUSTOMERNAME)
							  )
		FROM dbo.ITEMTRANSACTION_ARCHIVE trn
		INNER JOIN dbo.ITEMTRANSACTIONTYPE tt ON trn.TRTYPEID = tt.ITTID
		LEFT JOIN dbo.ITEMALLOCATION_ARCHIVE allo ON allo.IATRANSID = trn.TRID
		LEFT JOIN dbo.LABELS_PRODUCTION lp ON lp.LABELSERIALNBR = allo.IALABELSERIALNBR
		LEFT JOIN LIVESALESORDER_ARCHIVE lso ON lso.ORDERNBR = allo.IAORDERNBR
		WHERE TRTYPEID IN (3,4,5,6,7,9,10,11,12,13) 	 
		AND trn.TRITEMNBR = @ItemNbr
		AND CONVERT(DATE, TRDATETIME) >= @StartDate AND CONVERT(DATE, TRDATETIME) < = @EndDate

		UNION ALL
  
		SELECT 

			TRANSACTIONID = trn.trid ,
			TRANTYPE = tt.ITTDESC,
			TRANDATE = dbo.getShortDate(trn.TRDATETIME) + ' ' + dbo.getShortTime(trn.TRDATETIME),
			TRANCASES = trn.TRCASES,
			TRANORIGINALVALUE = ISNULL(trn.TRORIGINALVALUE,0),
			TRANNEWVALUE = ISNULL(trn.TRNEWVALUE,0),
			CUSTOMER = ISNULL(	lp.LABELCUSTOMERINFO, 
								CONVERT(VARCHAR , lso.ORDERNBR)  + ' : ' + UPPER (lso.CUSTOMERNAME)
							  )
	
		FROM LiveBagelAMPM_FEB_05.dbo.ITEMTRANSACTION trn
		INNER JOIN LiveBagelAMPM_FEB_05.dbo.ITEMTRANSACTIONTYPE tt ON trn.TRTYPEID = tt.ITTID
		LEFT JOIN LiveBagelAMPM_FEB_05.dbo.ITEMALLOCATION allo ON allo.IATRANSID = trn.TRID
		LEFT JOIN LiveBagelAMPM_FEB_05.dbo.LABELS_PRODUCTION lp ON lp.LABELSERIALNBR = allo.IALABELSERIALNBR
		LEFT JOIN LiveBagelAMPM_FEB_05.dbo.LiveSalesorder lso ON lso.ORDERNBR = allo.IAORDERNBR
		WHERE TRTYPEID IN (3,4,5,6,7,8,9,10,11,12,13) 	 
		AND trn.TRITEMNBR = @ItemNbr
		AND CONVERT(DATE, TRDATETIME) >= @StartDate AND CONVERT(DATE, TRDATETIME) < = @EndDate
		ORDER BY  1 DESC , 3 DESC 
	END 
	SET NOCOUNT OFF;
END
SET ANSI_NULLS OFF;
SET QUOTED_IDENTIFIER OFF;
GO
